[env]
TERM = "xterm-256color"

[window]
opacity = 0.8

[window.padding]
x = 2
y = 7

[font]
size = 14.2

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
