import = [
    # "~/.config/alacritty/rose-pine-moon.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

# [window]
# opacity = 0.9

[font]
size = 11.0

[font.normal]
family = "Fira Code"
style = "Regular"

# [font.bold]
# family = "Fira Code"
# style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"
