#!/usr/bin/env bash

# run from home dir

sudo apt install zsh

curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
sudo dpkg -i ripgrep_13.0.0_amd64.deb

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash

sudo apt-get -y install tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

curl -sS https://starship.rs/install.sh | sh
