#!/usr/bin/env bash

function symln() {
    local src dest
    src="$HOME/.dotfiles/$1"
    dest="$HOME/.config/$1"

    if [ -d "$dest" ]; then
        local response=""
        read -r -p "Do you want to overwrite existing dir? (y/n) " response </dev/tty

        if [[ $response != "y" ]]; then
            return
        fi
    fi

    ln -s "$src" "$dest"
}

declare -a dots=("alacritty" "bgs" "i3" "neofetch" "nvim" "picom" "polybar" "rofi")

for conf in "${dots[@]}"
do
    symln "$conf"
done
