#!/usr/bin/env bash

load_nvim() {
    local nvim_prev="/usr/local/share/nvim"
    local nvim_fallback="$HOME/.local/share/nvim"

    # use dev version unless stable is sent as arg
    local branch="${1:-"master"}"

    git checkout "$branch"

    if [ "$branch" == "master" ]; then
        git fetch
        local head upstream
        head=$(git rev-parse HEAD)
        upstream=$(git rev-parse master@\{upstream\})
        if [ "$head" == "$upstream" ]; then
            echo "=========Neovim is already upto date========="
            # long enough for me to see the message
            sleep 1.3
            return
        fi

        git pull origin --rebase
    fi

    sudo rm -rf "$nvim_prev"
    sudo rm -rf "$nvim_fallback"
    sudo make distclean

    make CMAKE_BUILD_TYPE=RelWithDebInfo
    sudo make install
}

nvim_dir="$HOME/tools/neovim"

if [ ! -d "$nvim_dir" ]; then
    echo "===============Getting Neovim==============="
    mkdir -p "$nvim_dir"
    git clone https://github.com/neovim/neovim "$nvim_dir"
fi

(
    cd "$nvim_dir" || return
    load_nvim "$1"
)

nvim .
