#!/usr/bin/env bash

languages=$(echo "rust go c cpp typescript javascript nodejs python lua" | tr ' ' '\n')

selected=$(printf "%s\ncore_utils" "$languages" | fzf)
read -r -p "ask: " query

query=$(echo "$query" | tr ' ' '+')

if printf "%s" "$languages" | grep -qs "$selected"; then
    curl "cht.sh/${selected}/${query}"
else
    curl cht.sh/"$query"
fi
