return {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    -- version = false,
    lazy = false,
    build = ":TSUpdate",

    opts = {
        ensure_installed = {
            "rust",
            "go",
            "ocaml",
            "zig",
            "c",
            "lua",
            "bash",
            "templ",
            "zig",
            "gleam",
            "typescript",
            "tsx",
            "jsdoc",
            "javascript",
            "python",
            "markdown",
            "vim",
            "vimdoc",
            "query",
            "sql",
            "hyprlang",
            "toml",
            "yaml",
            "json",
        },

        sync_install = false,
        auto_install = true,

        indent = { enable = true },
        highlight = { enable = true },
    },
}
